<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "congviec".
 *
 * @property int $id
 * @property string $tencongviec
 * @property string $motacongviec
 * @property int $nguoigiao
 * @property string $ngaygiao
 * @property string $ngayhoanthanh
 * @property string $danhgiacongviec
 * @property string $thoigiandanhgia
 * @property int $nguoinhan
 * @property int $status
 * @property int $duan_id
 * @property Baocaocongviec[] $baocaocongviecs
 * @property Duan $duan
 */
class Congviec extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'congviec';
    }
    public static $statuslist =[
        0=>'Đang thực hiện',
        1=>'Đã hoàn thành',
        2=>'Đang tạm dừng',
        3=>'Đã hủy',
        4=>'Chưa thực hiện'
    ];
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tencongviec', 'nguoigiao', 'ngaygiao', 'nguoinhan'], 'required'],
            [['tencongviec', 'motacongviec',"danhgiacongviec",'thoigiandanhgia'], 'string'],
            [['nguoigiao', 'nguoinhan', 'status', 'duan_id'], 'integer'],
            [['ngaygiao', 'ngayhoanthanh'], 'string', 'max' => 255],
            [['duan_id'], 'exist', 'skipOnError' => true, 'targetClass' => Duan::className(), 'targetAttribute' => ['duan_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tencongviec' => 'Công việc',
            'motacongviec' => 'Mô tả',
            'nguoigiao' => 'Người giao',
            'ngaygiao' => 'Ngày giao việc',
            'ngayhoanthanh' => 'Thời hạn',
            'nguoinhan' => 'Người nhận việc',
            'status' => 'Trạng thái',
            'danhgiacongviec' => 'Đánh giá công việc',
            'thoigiandanhgia' => 'Thời gian đánh giá',
            'duan_id' => 'Duan ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDuan()
    {
        return $this->hasOne(Duan::className(), ['id' => 'duan_id']);
    }
    public function getBaocaocongviecs()
    {
        return $this->hasMany(Baocaocongviec::className(), ['congviec_id' => 'id'])->where(['parent'=>-1])->orderBy("id desc");
    }
    public function getDateRemaining(){

        if(empty($this->ngayhoanthanh)){
            return 0;
        }
        date_default_timezone_set("Asia/Ho_Chi_Minh");
        $date = date_create_from_format("Y-m-d",$this->ngayhoanthanh);
        if($date){
            $s=($date)->diff(date_create_from_format("Y-m-d",date("Y-m-d")))->format("%r%a");
            return (int)$s;
        }
        return 0;
    }
    public function checkExpire(){
        return $this->getDateRemaining()<=0;
    }
    public function getStatusTextNoFormat(){
        $statuslist =[
            0=>'Đang thực hiện',
            1=>'Đã hoàn thành',
            2=>'Đang tạm dừng',
            3=>'Đã hủy',
            4=>'Chưa thực hiện'
        ];
        $statuslistTextClass =[
            0=>'label label-primary',
            1=>'label label-success',
            2=>'label label-warning',
            3=>'label label-danger',
            4=>'label label-primary'
        ];
        return $statuslist[$this->status];
    }
    public function getStatusText(){
        $statuslist =[
            0=>'Đang thực hiện',
            1=>'Đã hoàn thành',
            2=>'Đang tạm dừng',
            3=>'Đã hủy',
            4=>'Chưa thực hiện'
        ];
        $statuslistTextClass =[
            0=>'label label-primary',
            1=>'label label-success',
            2=>'label label-warning',
            3=>'label label-danger',
            4=>'label label-primary'
        ];
        return "<span data-type='select' data-pk='".$this->id."' data-value='".$this->status."' data-original-title='Update' data-source='/admin/site/groups' class='editable editable-click ".$statuslistTextClass[$this->status]."'>".$statuslist[$this->status]."</span>";
    }
    public function beforeSave($insert)
    {
        if($this->isNewRecord){

        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function checkIsGranted(){
        return !is_null(\common\models\Nguoinhanviec::findOne(['congviecid'=>$this->id,'nguoiduocgan'=>Yii::$app->user->id]));
    }
}
