<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "partner".
 *
 * @property int $id
 * @property string $name
 * @property string $image
 * @property string $url
 * @property int $position
 * @property int $ord
 * @property int $active
 * @property int $lang_id
 */
class Partner extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    const HEADER = 1;
    const BOTTOM = 2;
    const DICHVU = 3;

    public static function tableName()
    {
        return 'partner';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['position', 'name'], 'required'],
            [['image', 'url'], 'string'],
            [['position', 'ord', 'active', 'lang_id'], 'integer'],
            [['name'], 'string', 'max' => 200],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên đối tác',
            'image' => 'Ảnh',
            'url' => 'Đường dẫn',
            'position' => 'Vị trí',
            'ord' => 'Thứ tự',
            'active' => 'Hoạt động',
            'lang_id' => 'Lang ID',
        ];
    }

    public static function getPosition()
    {
        return [
            self::HEADER => 'Partner',
            self::BOTTOM => 'Advertise',
            self::DICHVU => 'Dịch Vụ',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {


        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        $path = dirname(dirname(__DIR__)) . '/images/partner/' . $this->image;
        if (is_file($path))
            unlink($path);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public static function getAds()
    {
        $ads = self::find()->where(['position' => 2, 'active' => 1])->orderBy(['ord' => SORT_ASC])->all();
        return $ads;
    }

    public function beforeSave($insert)
    {
        $file = UploadedFile::getInstanceByName('anhpartner');
        if (!is_null($file)) {
            $this->image = '/images/partner/' . \func::taoduongdan(time() . "-" . $file->name);
            $path = dirname(dirname(__DIR__)) . $this->image;
            $file->saveAs($path);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public  static function getPartner($pos)
    {
        return self::find()->where(['position' => $pos, 'active' => 1])->orderBy(['id' => SORT_ASC])->all();
    }
}